default: &default
  <<: *common
  subject_prefix_for_outgoing_emails: Wheel
  mailer_default_from_email: "'Wheel' <notifications@wheel.com>"
  support_email: support@wheel.com
  host: <%= ENV['APP_URL'] || ENV['HEROKU_APP_URL'] %>

development:
  <<: *default
  secret_key_base: 3193ce62de10f78da223e95760dd6c08523cd78204b4d8dc8bb119faf8847adceb70aadce1288ffd8e6232afb3a704c60a75feb024ab937de989322f4e64a385
  devise:
    secret_key: c0cd8c380935936ff6c6bfb7b0f0ed3f3a2d66d7d7b445394a879dea71bfb5711799c7840e7d4fd93fe8a0983c4f27fd30caebea879dff734c15ff1696262144

test:
  <<: *default
  secret_key_base: 08523cd7820d8e6232afb3a704c60a75feb024ab937de989322f4e64a3854b4d8dc8bb119faf8847adceb70aadce1288ff3193ce62de10f78da223e95760dd6c
  mailer_delivery_method: :test
  devise:
    secret_key: 5394a879dea71bfbc0cd8c380935936ff6c6b5711799c7840e7d4fd93fe8a0983c4f27fd30caebea879dff734c15ff1696262144fb7b0f0ed3f3a2d66d7d7b44

heroku:
  <<: *default
  store_uploaded_assets_in: aws_s3
  secret_key_base: b731f261415e6f13e3e3e5a6726ee163707938f38514331fc2a67eda3800dd428bfe2a0c3b4ed83cf99e7df643e93b450511f81e05556712128ae786559ada6e
  devise:
    secret_key: ecd10b29124e0b3c68890e6c019566fc8a4b3f3bc519eb99d3d06d05f0a7ce3df1522472eb90e1ffc56b03119a9ed5e3e6e412bca67003c2ee449715fd98b94c

staging:
  <<: *default
  store_uploaded_assets_in: aws_s3
  secret_key_base: b731f261415e6f13e3e3e5a6726ee163707938f38514331fc2a67eda3800dd428bfe2a0c3b4ed83cf99e7df643e93b450511f81e05556712128ae786559ada6e
  devise:
    secret_key: ecd10b29124e0b3c68890e6c019566fc8a4b3f3bc519eb99d3d06d05f0a7ce3df1522472eb90e1ffc56b03119a9ed5e3e6e412bca67003c2ee449715fd98b94c

production:
  <<: *default
  store_uploaded_assets_in: aws_s3
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  devise:
    secret_key: <%= ENV['DEVISE_KEY'] %>

common: &common
  store_uploaded_assets_in: filesystem
  mailer_delivery_method: :smtp
  redis_url: <%= ENV['REDISTOGO_URL'] || ENV['REDIS_URL'] %>
  cypress:
    record_key: <%= ENV['CYPRESS_RECORD_KEY'] %>
    auth_token: <%= ENV['CYPRESS_AUTH_TOKEN'] %>
  sidekiq:
    username: <%= ENV['SIDEKIQ_USERNAME'] %>
    password: <%= ENV['SIDEKIQ_PASSWORD'] %>
  mailer:
    smtp_settings:
      user_name: <%= ENV['MAILGUN_USERNAME'] %>
      password: <%= ENV['MAILGUN_PASSWORD'] %>
      domain: <%= ENV['MAILGUN_DOMAIN'] %>
      address: smtp.mailgun.org
      authentication: plain
      enable_starttls_auto: true
  aws_s3:
    access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
    bucket_name: <%= ENV['AWS_S3_BUCKET_NAME'] %>
